tracing:
  log_level: info

runtime:
  n_cores: 0
  thread_name: slim-data-plane
  drain_timeout: 10s

services:
  slim/0:
    dataplane:
      servers:
        - endpoint: "0.0.0.0:46357"
          tls:
            insecure: true
          auth:
            type: none
